"""PDF generation utilities for pre-match briefing export."""

from __future__ import annotations

from fpdf import FPDF


class BriefingPDF(FPDF):
    def header(self):
        # Draw dark slate header banner
        self.set_fill_color(30, 41, 59) # Slate-800
        self.rect(0, 0, 210, 32, "F")
        
        self.set_y(8)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 6, "FIFA WORLD CUP MATCH ANALYSIS", ln=True, align="C")
        
        self.set_font("Helvetica", "I", 10)
        self.cell(0, 6, "Official Pre-Match Intelligence Briefing", ln=True, align="C")
        
        # Reset margins for main page body
        self.set_y(38)
        
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by FIFA WC Predictor Engine · Confidential", align="C")


def generate_prematch_pdf(
    home_team: str,
    away_team: str,
    analysis: dict,
) -> bytes:
    """Generate a premium pre-match report PDF using fpdf2 and return the bytes."""
    pdf = BriefingPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # 1. Main Match Title
    pdf.set_text_color(30, 41, 59)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, f"{home_team} vs {away_team}", ln=True, align="C")
    
    # Details line
    stage_str = str(analysis.get("stage", "Group Stage")).replace("_", " ").title()
    venue_str = str(analysis.get("venue", "TBD"))
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Competition Stage: {stage_str} | Venue: {venue_str}", ln=True, align="C")
    pdf.ln(6)
    
    # 2. Section: Model Predictions
    pdf.set_fill_color(241, 245, 249) # Slate-100
    pdf.set_draw_color(203, 213, 225) # Slate-300
    pdf.set_text_color(30, 41, 59)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "  1. MODEL PREDICTION PROBABILITIES", fill=True, border="B", ln=True)
    pdf.ln(3)
    
    # Table headers
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(226, 232, 240) # Slate-200
    pdf.cell(60, 7, "Outcome", border=1, align="C", fill=True)
    pdf.cell(60, 7, "Model Probability", border=1, align="C", fill=True)
    pdf.cell(70, 7, "Expected xG", border=1, align="C", fill=True)
    pdf.ln()
    
    pdf.set_font("Helvetica", "", 9)
    # Win
    pdf.cell(60, 7, f"{home_team} Win", border=1, align="C")
    pdf.cell(60, 7, f"{analysis.get('prob_home_win', analysis.get('prob_home', 0.0)):.1%}", border=1, align="C")
    pdf.cell(70, 7, f"{analysis.get('expected_xg_home', 0.00):.2f}" if analysis.get('expected_xg_home') is not None else "—", border=1, align="C")
    pdf.ln()
    # Draw
    pdf.cell(60, 7, "Draw", border=1, align="C")
    pdf.cell(60, 7, f"{analysis.get('prob_draw', 0.0):.1%}", border=1, align="C")
    pdf.cell(70, 7, "—", border=1, align="C")
    pdf.ln()
    # Loss
    pdf.cell(60, 7, f"{away_team} Win", border=1, align="C")
    pdf.cell(60, 7, f"{analysis.get('prob_away_win', analysis.get('prob_away', 0.0)):.1%}", border=1, align="C")
    pdf.cell(70, 7, f"{analysis.get('expected_xg_away', 0.00):.2f}" if analysis.get('expected_xg_away') is not None else "—", border=1, align="C")
    pdf.ln()
    
    top_score = analysis.get("top_scoreline", "—")
    pdf.ln(2)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 5, f"Likeliest Scoreline Result: {top_score}", ln=True)
    pdf.ln(4)
    
    # 3. Section: Elo ratings
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(0, 7, "  2. TEAM RATINGS & STRENGTHS", fill=True, border="B", ln=True)
    pdf.ln(3)
    
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(226, 232, 240)
    pdf.cell(95, 7, f"{home_team}", border=1, align="C", fill=True)
    pdf.cell(95, 7, f"{away_team}", border=1, align="C", fill=True)
    pdf.ln()
    
    pdf.set_font("Helvetica", "", 9)
    elo_h = f"{analysis.get('elo_home', 1500):.0f}" if analysis.get('elo_home') else "—"
    elo_a = f"{analysis.get('elo_away', 1500):.0f}" if analysis.get('elo_away') else "—"
    pdf.cell(95, 7, f"Elo Rating: {elo_h}", border=1, align="C")
    pdf.cell(95, 7, f"Elo Rating: {elo_a}", border=1, align="C")
    pdf.ln()
    pdf.ln(4)
    
    # 4. Section: SHAP Narrative Insights
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(0, 7, "  3. SHAP EXPLAINER & KEY FEATURE FACTORS", fill=True, border="B", ln=True)
    pdf.ln(3)
    
    narrative = analysis.get("narrative", "")
    if not narrative and "_analysis" in analysis:
        narrative = analysis["_analysis"].get("narrative", "")
        
    if narrative:
        # Strip markdown bold tags for PDF printer compatibility
        clean_narrative = narrative.replace("**", "").strip()
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 4.5, clean_narrative)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 5, "No feature insights narrative generated for this fixture.", ln=True)
        
    pdf.ln(4)
    
    # 5. Disclaimer / Note
    pdf.set_draw_color(226, 232, 240)
    pdf.set_fill_color(248, 250, 252) # Gray background
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(
        0, 4,
        "Disclaimer: This report contains probabilistic projections generated by a machine learning model trained "
        "on historical international results since 2000. These values are estimates and should not be used as financial "
        "or betting advice. Match outcomes are subject to significant variance.",
        border=1, fill=True, align="C"
    )
    
    return bytes(pdf.output())
